# Generated by Django 4.0.4 on 2022-07-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shoulder', models.PositiveIntegerField()),
                ('Body_Length', models.PositiveIntegerField()),
                ('Chest', models.PositiveIntegerField()),
                ('Waist', models.PositiveIntegerField()),
                ('Bottom_width', models.PositiveIntegerField()),
                ('Sleeve_length', models.PositiveIntegerField()),
            ],
        ),
    ]
