# Generated by Django 4.0.4 on 2022-07-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_uploadfile_custom_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom',
            options={'verbose_name_plural': 'customs'},
        ),
    ]
